### ISSUE TITLE
Question about Usage

### ISSUE THREAD

**Issue by gregkcarson** [AlsidOfficial/WSUSpendu#1]
Just a question about usage of this tool.

To be clear I have not read your white paper or done research on this.  Here you state:

"Some limitations apply for using this tool, mainly the binary used by the update must be signed by Microsoft, or more generally, by a certificate approved for code signing in the Trusted Root Certification Authorities or the Trusted Publishers stores. You will also, obviously, need to get access to the WSUS database."

If you have shell and domain admin creds in an environment where an enterprise is using it's own internal PKI and have pushed their trusted root/issuing CA certs (with 'intended purpose' set to 'ALL' when viewed in MMC certificate store) to all supplicant client systems, could you export that cert and use  it to sign a malicious update that could then be distributed using WSUSpendu? You could export any cert with 'code signing privileges' and use it to this end? Theoretically lots of systems from DIFFERENT enterprises may have the same root CA certs so you don't even need to get admin rights to export the cert you want to use to sign the malicious executable.

I'm just trying to understand how much of a limitation your statement actually is.

**Comment by Aorimn** [comment]
Hi,
In a general case where an enterprise uses its own internal PKI and have pushed their trusted root/issuing CA certs, with 'Intended Purposes' set at least to 'Code Signing', you could export that cert if you find where the private signing key is (which is hopefully not stored on the WSUS server itself). 
Exporting the certificates from the MMC usually exports only the public part of the key, not the private one. Of course, some enterprises might fail at this step and push the public and private keys to the clients, but I know it isn't the case for many of them.

**Comment by gregkcarson** [comment]
Right.

So a potential scenario would be if an Enterprise is using 802.1x wireless authentication with EAP-TLS. Supplicants would receive cert template from internal PKI ADCS and generate local private keys. If the cert template used has code signing rights and attacker has local admin then even if cert is marked mom exportable you can use popular jailbreak techniques ( https://github.com/iSECPartners/jailbreak ) to get cert and private key for use with your tool.

Anyways just sharing some thought :) very interesting tool, good job!
