### ISSUE TITLE
Connection : Login failed for user 'Domain\Administrator'.

### ISSUE THREAD

**Issue by dimpol** [AlsidOfficial/WSUSpendu#2]
Hi, I am trying to check how the script works in my lab domain.

I am running the script inside WSUS and having logged in with the Domain Admin account. 
I receive the following...
Can you please help me locate the root cause of this issue?

I did a default installation of WSUS and haven't specified an SQL Server instance during installation. That means that it only uses the WID database and that's why I receive the error?

Connection : Login failed for user 'Domain\Administrator'.
At C:\Users\Administrator\Desktop\WSUSpendu\WSUSpendu\WSUSpendu.ps1:597 char:24
+ $g_SQLCmd.Connection = Connection
+                        ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connection

**Comment by r1-** [comment]
I installed a domain controller and joined my WSUS server in this domain. I tried to connect with domain administrator but no error appeared. 
With default installation of WSUS, and if you not specified external database, WSUS uses WID database. 
Are you sure your WSUS server joined the domain ?

**Comment by dimpol** [comment]
I renamed my domain name lately, so maybe this is confusing things. Closing the issue. thank you very much for your time to check this out !!
