### ISSUE TITLE
Have u tried use this to deliver bginfo, it doesn't work.

### ISSUE THREAD

**Issue by uemahra** [AlsidOfficial/WSUSpendu#5]
for psexec, the script works, but for bginfo.exe, I tried a lot of version, none of them can work, but if I copy a bginfo.exe to the pc, and run bginfo.exe \\\ip\folder\filename.bgi /timer:0 /nolicprompt. it works. why. I assume because NT AUTHORITY\SYSTEM can not run bginfo

**Comment by Aorimn** [comment]
The most likely issue without having any other information is the credentials used to connect to the share:
- in the case of WSUSpendu, the update is executed by the computer, hence the computer account being used to access the share.
- when run by hand, the binary is executed in the user's context, hence the user account being used to access the share.

**Comment by uemahra** [comment]
The net share I configured allows everyone log on and read. the share is on win7, and the command line is run on a win10.

**Comment by Aorimn** [comment]
Then might I suggest replacing bginfo with [scriptrunner](https://twitter.com/Aorimn/status/897009461264433152) or [something else](https://twitter.com/Aorimn/status/895302949475430400)?

**Comment by Aorimn** [comment]
I'm closing this issue as the question seems to have been answered. Feel free to continue the discussion afterward on this subject.
